CREATE CONSTRAINT user_email IF NOT EXISTS FOR(u:User) REQUIRE u.email IS UNIQUE;
CREATE CONSTRAINT group_name IF NOT EXISTS FOR(g:Group) REQUIRE g.name IS UNIQUE;
CREATE CONSTRAINT post_id IF NOT EXISTS FOR(p:Post) REQUIRE p.id IS UNIQUE;
CREATE CONSTRAINT community_name IF NOT EXISTS FOR(c:Community) REQUIRE c.name IS UNIQUE;

CREATE INDEX user_id IF NOT EXISTS FOR(u:User) ON (u.id);
CREATE INDEX post_created_at IF NOT EXISTS FOR(p:Post) ON (p.createdAt);